name: crypto-bot-${MAVEN_PROFILE:-dev}

services:
  market-watcher-service:
    container_name: market-watcher-service-${MAVEN_PROFILE:-dev}
    build:
      context: ./market-watcher-service/
      dockerfile: Dockerfile
      args:
        MAVEN_PROFILE: ${MAVEN_PROFILE:-dev}
        PORT: ${APP_PORT:-8082}
    ports:
      - "${APP_PORT:-8082}:${APP_PORT:-8082}"
    volumes:
      - ./logs:/market-watcher/logs
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
      - SERVER_PORT=${APP_PORT:-8082}
    networks:
      - crypto-bot-network

  postgres:
    container_name: postgres-db-${MAVEN_PROFILE:-dev}
    image: postgres:17.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: marketdatadb
      POSTGRES_USER: ats_postgres_user
      POSTGRES_PASSWORD: ats_postgres_pass
    #volumes:
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the initialization script
    networks:
      - crypto-bot-network

networks:
  crypto-bot-network:
    driver: bridge